name: CI/CD Workflow

on:
  push:
    branches:
      - 'feature'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Flake8 Linter
        run: |
          pip install flake8
          flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run pytest
        run: |
          pip install pytest
          pytest

  merge:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Merge Feature Branch into Dev
        run: |
          git fetch origin
          git checkout dev
          git merge --no-ff --allow-unrelated-histories --strategy=recursive --strategy-option=ours $(echo "${{ github.ref }}" | sed 's/refs\/heads\///') || true
          git add .  # Add all changes (including conflict resolutions) to the staging area
          git commit -m "Merge feature branch into dev" || echo "No changes to commit"
          git push origin dev
